version: "3.5"

services:
  db:
    image: mysql:8.0.32
    command: [
      '--default-authentication-plugin=mysql_native_password',
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: app
    user: ${PUID}:${PGID}
    ports:
      - "3333:3306"
    volumes:
      - data_test_payments:/var/lib/mysql

  nginx:
    build:
      context: ./docker/nginx
      args:
        - UID=${PUID}
        - GID=${PGID}
        - USER=${PUSER}
        - GROUP=${PGROUP}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    depends_on: [app]
    volumes:
      - ./:/var/www:rw
      - sock_test_payments:/var/run

  app:
    build:
      context: ./docker/php-fpm8.2
      args:
        - UID=${PUID}
        - GID=${PGID}
        - USER=${PUSER}
        - GROUP=${PGROUP}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=DebugTestPayments"
    depends_on: [db]
    volumes:
      - ./:/var/www
      - ./docker/php-fpm8.2/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - sock_test_payments:/var/run

volumes:
  sock_test_payments:
  data_test_payments:

